development:
  cloud_name: htrung1303
  api_key: <%= ENV["cloudinary_api"] %>
  api_secret: <%= ENV["cloudinary_secret"] %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: htrung1303
  api_key: <%= ENV["cloudinary_api"] %>
  api_secret: <%= ENV["cloudinary_secret"] %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: htrung1303
  api_key: <%= ENV["cloudinary_api"] %>
  api_secret: <%= ENV["cloudinary_secret"] %>
  enhance_image_tag: true
  static_file_support: false
